os: linux
dist: focal
 
vm:
 use:
  name: my_testuser1_name

vm:
 use:
  name: my_testuser1_name

vm:
 use:
  name: my_testuser1_name

vm:
 use:
  name: my_testuser1_name

vm:
 use:
  name: my_testuser1_name

vm:
 use:
  name: my_testuser1_name

vm:
 use:
  name: my_testuser1_name

vm:
 use:
  name: my_testuser1_name

vm:
 use:
  name: my_testuser1_name

 
before_install:
  - sudo apt-get -y install libxml2-dev
 
addons:
  apt:
    update: true
 
script:
  - echo "TEST"
  
