jobs:
  include:
    - os: linux
      dist: focal
      vm:
        create:
          name: kakashi_image
      before_install:
        - sudo apt-get -y install libxml2-dev
      addons:
        apt:
          update: true
