os: linux
dist: focal

vm:
  use:
    name: Asta_image #use_existing_image
  size: large

before_install:
  - sudo apt-get -y install libxml2-dev

addons:
  apt:
    update: true

script:
  - echo "OK8"
