os: linux
dist: focal
 
vm:
  create:
    name: error_state_imageeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
 
before_install:
  - sudo apt-get -y install libxml2-dev
 
addons:
  apt:
    update: true
 
script:
  - echo "TEST"
  
