jobs:
  include:
    - stage: use custom image
      os: linux
      dist: focal
      vm:
        create:
          name: hinata_image
      before_install:
        - sudo apt-get -y install libxml2-dev
      addons:
        apt:
          update: true
